---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: User
metadata:
  name: gitops-test-user
  labels:
    example: "true"
spec:
  forProvider:
    tags:
      - key: k1
        value: v1
  providerConfigRef:
    name: default
